-- Auto-generated by Matugen

local colors = {
  background = "rgb({{colors.background.default.hex_stripped}})",
  on_background = "rgb({{colors.on_background.default.hex_stripped}})",
  surface = "rgb({{colors.surface.default.hex_stripped}})",
  surface_variant = "rgb({{colors.surface_variant.default.hex_stripped}})",
  on_surface = "rgb({{colors.on_surface.default.hex_stripped}})",
  primary = "rgb({{colors.primary.default.hex_stripped}})",
  primary_container = "rgb({{colors.primary_container.default.hex_stripped}})",
  on_primary = "rgb({{colors.on_primary.default.hex_stripped}})",
  secondary = "rgb({{colors.secondary.default.hex_stripped}})",
  secondary_container = "rgb({{colors.secondary_container.default.hex_stripped}})",
  error = "rgb({{colors.error.default.hex_stripped}})",
  shadow = "rgb({{colors.shadow.default.hex_stripped}})"
}

return colors
