-- Auto-generated by Matugen
local background = rgb({{colors.background.default.hex_stripped}})
local on_background = rgb({{colors.on_background.default.hex_stripped}})

local surface = rgb({{colors.surface.default.hex_stripped}})
local surface_variant = rgb({{colors.surface_variant.default.hex_stripped}})
local on_surface = rgb({{colors.on_surface.default.hex_stripped}})

local primary = rgb({{colors.primary.default.hex_stripped}})
local primary_container = rgb({{colors.primary_container.default.hex_stripped}})
local on_primary = rgb({{colors.on_primary.default.hex_stripped}})

local secondary = rgb({{colors.secondary.default.hex_stripped}})
local secondary_container = rgb({{colors.secondary_container.default.hex_stripped}})

local error = rgb({{colors.error.default.hex_stripped}})

local shadow = rgb({{colors.shadow.default.hex_stripped}})
