background = 0xee{{colors.background.default.hex_stripped}}
base = 0xff{{colors.primary.default.hex_stripped}}
text = 0xff{{colors.on_primary.default.hex_stripped}}
accent = 0xff{{colors.on_background.default.hex_stripped}}
