# --- Mako Dynamic Configuration ---
max-visible=5
sort=-time
layer=top
anchor=top-right

# Geometry
width=350
margin=20
padding=15
border-size=2
border-radius=12

# Fonts & Progress Bars
font=Noto Sans 10
progress-color=over {{colors.primary.default.hex}}

# System Colors injected by Matugen
background-color={{colors.background.default.hex}}e6
text-color={{colors.on_background.default.hex}}
border-color={{colors.primary.default.hex}}

[urgency=high]
border-color={{colors.error.default.hex}}
default-timeout=0

[urgency=low]
default-timeout=3000
