[General]
Background="Backgrounds/current_wall.png"
ScaleImageCropped=true
FullBlur=false

AccentColour="{{colors.primary.default.hex}}"
MainColour="{{colors.on_background.default.hex}}"
BackgroundColour="{{colors.background.default.hex}}"
ButtonBackgroundColour="{{colors.primary_container.default.hex}}"
TextBoxBackgroundColour="{{colors.surface_variant.default.hex}}"
